[package]
name = "my-onnx"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
bytes = "1.7.1"
delegate = "0.13.4"
derive_more = { version = "2.0.1", features = ["from"] }
id-arena = "2.2.1"
image = "0.25.5"
indexmap = "2.7.1"
inkwell = { version = "0.5.0", features = ["llvm18-0-prefer-static"] }
itertools = "0.13.0"
libloading = "0.8.6"
ndarray = "0.16.0"
num-integer = "0.1.46"
prost = "0.13.1"
rand = { version = "0.8.5", features = ["small_rng"] }
rayon = "1.10.0"
serde = "1.0.219"
serde_derive = "1.0.219"
smallvec = "1.15.0"
strum = "0.26.3"
strum_macros = "0.26.4"
tempfile = "3.15.0"
typed-builder = "0.21.0"

[build-dependencies]
prost-build = "0.13.1"

[dev-dependencies]
insta = { version = "1.43.1", features = ["yaml"] }
