[package]
name = "my-onnx-llm"
version = "0.1.0"
edition = "2021"

[features]
default = ["cuda"]
cuda = ["my-onnx/cuda"]
local = ["my-onnx/local"]

[dependencies]
my-onnx = { path = "../.." }
log = "0.4.29"
thiserror = "2"
tokenizers = { version = "0.20", default-features = false, features = ["onig"] }
