[package]
name = "my-onnx-llm"
version = "0.1.0"
edition = "2021"

[features]
default = ["cuda"]
cuda = ["my-onnx/cuda"]
local = ["my-onnx/local"]

[dependencies]
my-onnx = { path = "../.." }
log = "0.4.29"
thiserror = "2"
tokenizers = { version = "0.20", default-features = false, features = ["onig"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
safetensors = "0.7.0"
memmap2 = "0.9.10"
libloading = "0.9.0"
itertools = "0.14.0"
minijinja = { version = "2.19.0", default-features = false, features = ["builtins", "serde"] }
