[package]
name = "my-nn-engine-ui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "web-server"
path = "src/main.rs"

[dependencies]
my-nn-engine = { path = "../..", default-features = false }

tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.5", features = ["cors"] }
env_logger = "0.11"
log = "0.4.29"

# gRPC dependencies
tonic = "0.12"
tonic-web = "0.12"
prost = "0.13.1"
http = "1"

[dev-dependencies]
tempfile = "3.15.0"

[build-dependencies]
tonic-build = "0.12"
