use std::path::Path;
use std::path::PathBuf;

use my_nn_engine::options::Options;
use my_nn_engine::options::PrefetchPolicy;
use my_nn_engine::options::Target;
use my_nn_engine_llm::build_decoder;
use my_nn_engine_llm::quantize::cast_safetensors_bf16_dir;
use my_nn_engine_llm::BuildOptions;
use my_nn_engine_llm::HfConfig;
use my_nn_engine_llm::HfWeights;
use my_nn_engine_llm::LlmSession;
use my_nn_engine_llm::ModelSpec;
use tokenizers::Tokenizer;

fn model_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../models/hf/tiny-llama-random")
}

// Reference generated by `scripts/gen_llm_reference.py models/hf/tiny-llama-random "Hello" 8`.
// The same IDs are produced under bf16 for this small model (verified with
// transformers torch_dtype=bfloat16).
const PROMPT: &str = "Hello";
const EXPECTED_NEW_IDS: &[u32] = &[3038, 25190, 6074, 6566, 21376, 8002, 12090, 28535];
const STREAM_SINK: usize = 4;
const STREAM_WINDOW: usize = 28;

fn run_with_dir(dir: &Path, target: Target) {
    let config = HfConfig::from_path(dir.join("config.json")).unwrap();
    let hf = HfWeights::from_dir(dir).unwrap();
    let spec = ModelSpec::from_hf(&config, &hf).unwrap();

    let max_seq_len = STREAM_SINK + STREAM_WINDOW;
    let llama_opts = BuildOptions::builder().streaming_kv(true).build();
    let r = build_decoder(&config, &spec, max_seq_len, &llama_opts);
    let opts = Options::builder().target(target).build();
    let tokenizer = Tokenizer::from_file(dir.join("tokenizer.json")).unwrap();
    let mut llm = LlmSession::for_llama_streaming(
        r.graph,
        None,
        r.kv_cache_names,
        tokenizer,
        &opts,
        max_seq_len,
        config.eos_token_id,
        STREAM_SINK,
        STREAM_WINDOW,
    )
    .unwrap();

    let new_ids = llm.generate_ids(PROMPT, EXPECTED_NEW_IDS.len()).unwrap();
    assert_eq!(new_ids, EXPECTED_NEW_IDS);
}

fn run(target: Target) {
    run_with_dir(&model_dir(), target);
}

fn run_bf16(target: Target) {
    let src = model_dir();
    let tmp = tempfile::TempDir::new().unwrap();
    cast_safetensors_bf16_dir(&src, tmp.path().join("model.safetensors")).unwrap();
    for name in [
        "config.json",
        "tokenizer.json",
        "generation_config.json",
        "special_tokens_map.json",
        "tokenizer_config.json",
        "chat_template.jinja",
    ] {
        let from = src.join(name);
        if from.exists() {
            std::fs::copy(&from, tmp.path().join(name)).unwrap();
        }
    }
    run_with_dir(tmp.path(), target);
}

#[test]
fn cpu() {
    run(Target::CPU);
}

#[test]
fn cpu_multi_turn_prefill_matches_decode_only() {
    fn build_session(dir: &Path, prefill_len: Option<usize>) -> LlmSession {
        let config = HfConfig::from_path(dir.join("config.json")).unwrap();
        let hf = HfWeights::from_dir(dir).unwrap();
        let spec = ModelSpec::from_hf(&config, &hf).unwrap();

        let max_seq_len = STREAM_SINK + STREAM_WINDOW;
        let llama_opts = BuildOptions::builder().streaming_kv(true).build();
        let r = build_decoder(&config, &spec, max_seq_len, &llama_opts);
        let opts = Options::builder().target(Target::CPU).build();
        let tokenizer = Tokenizer::from_file(dir.join("tokenizer.json")).unwrap();

        let prefill = prefill_len.map(|len| {
            (
                build_decoder(
                    &config,
                    &spec,
                    max_seq_len,
                    &BuildOptions {
                        prefill_len: Some(len),
                        ..llama_opts.clone()
                    },
                )
                .graph,
                len,
            )
        });
        LlmSession::for_llama_streaming(
            r.graph,
            prefill,
            r.kv_cache_names,
            tokenizer,
            &opts,
            max_seq_len,
            config.eos_token_id,
            STREAM_SINK,
            STREAM_WINDOW,
        )
        .unwrap()
    }

    let dir = model_dir();

    let mut decode_only = build_session(&dir, None);
    let ref1 = decode_only.generate_ids(PROMPT, 1).unwrap();
    let ref2 = decode_only.generate_ids(" world", 3).unwrap();
    let ref_ids: Vec<u32> = ref1.into_iter().chain(ref2).collect();

    let mut with_prefill = build_session(&dir, Some(4));
    let p1 = with_prefill.generate_ids(PROMPT, 1).unwrap();
    let past_after_first = with_prefill.past_len();
    assert!(0 < past_after_first);
    let p2 = with_prefill.generate_ids(" world", 3).unwrap();
    assert!(past_after_first < with_prefill.past_len());
    let prefill_ids: Vec<u32> = p1.into_iter().chain(p2).collect();

    assert_eq!(ref_ids, prefill_ids);
}

#[test]
fn cpu_bf16() {
    run_bf16(Target::CPU);
}

#[cfg(feature = "cuda")]
#[test]
fn cuda() {
    run(Target::CUDA(PrefetchPolicy::Disabled));
}

#[cfg(feature = "cuda")]
#[test]
fn cuda_streaming_runs_past_window() {
    let dir = model_dir();
    let config = HfConfig::from_path(dir.join("config.json")).unwrap();
    let hf = HfWeights::from_dir(&dir).unwrap();
    let spec = ModelSpec::from_hf(&config, &hf).unwrap();

    let max_seq_len = 32;
    let sink = 4;
    let window = 16;
    let max_active = sink + window;

    let llama_opts = BuildOptions::builder().streaming_kv(true).build();
    let r = build_decoder(&config, &spec, max_seq_len, &llama_opts);
    assert!(r.streaming.is_some());

    let opts = Options::builder()
        .target(Target::CUDA(PrefetchPolicy::Disabled))
        .build();
    let tokenizer = Tokenizer::from_file(dir.join("tokenizer.json")).unwrap();
    let mut llm = LlmSession::for_llama_streaming(
        r.graph,
        None,
        r.kv_cache_names,
        tokenizer,
        &opts,
        max_seq_len,
        config.eos_token_id,
        sink,
        window,
    )
    .unwrap();

    let want = max_active + 10;
    let new_ids = llm.generate_ids(PROMPT, want).unwrap();
    assert_eq!(new_ids.len(), want);
    assert!(
        max_active < llm.past_len(),
        "past_len {} must exceed sink+window {} to exercise the ring",
        llm.past_len(),
        max_active,
    );
}

#[cfg(feature = "cuda")]
#[test]
fn cuda_streaming_quant_runs_past_window() {
    let dir = model_dir();
    let config = HfConfig::from_path(dir.join("config.json")).unwrap();
    let hf = HfWeights::from_dir(&dir).unwrap();
    let spec = ModelSpec::from_hf(&config, &hf).unwrap();

    let max_seq_len = 32;
    let sink = 4;
    let window = 16;
    let max_active = sink + window;

    let llama_opts = BuildOptions::builder()
        .quant_kv_cache(true)
        .streaming_kv(true)
        .build();
    let r = build_decoder(&config, &spec, max_seq_len, &llama_opts);
    assert!(r.streaming.is_some());

    let opts = Options::builder()
        .target(Target::CUDA(PrefetchPolicy::Disabled))
        .build();
    let tokenizer = Tokenizer::from_file(dir.join("tokenizer.json")).unwrap();
    let mut llm = LlmSession::for_llama_streaming(
        r.graph,
        None,
        r.kv_cache_names,
        tokenizer,
        &opts,
        max_seq_len,
        config.eos_token_id,
        sink,
        window,
    )
    .unwrap();

    let want = max_active + 10;
    let new_ids = llm.generate_ids(PROMPT, want).unwrap();
    assert_eq!(new_ids.len(), want);
    assert!(
        max_active < llm.past_len(),
        "past_len {} must exceed sink+window {} to exercise the ring",
        llm.past_len(),
        max_active,
    );
}

#[cfg(feature = "cuda")]
fn run_streaming_prefill_smoke(quant_kv_cache: bool) {
    let dir = model_dir();
    let config = HfConfig::from_path(dir.join("config.json")).unwrap();
    let hf = HfWeights::from_dir(&dir).unwrap();
    let spec = ModelSpec::from_hf(&config, &hf).unwrap();

    let max_seq_len = 32;
    let sink = 4;
    let window = 16;
    let max_active = sink + window;
    let prefill_len = 4;

    let llama_opts = BuildOptions::builder()
        .quant_kv_cache(quant_kv_cache)
        .streaming_kv(true)
        .build();
    let r = build_decoder(&config, &spec, max_seq_len, &llama_opts);
    let p = build_decoder(
        &config,
        &spec,
        max_seq_len,
        &BuildOptions {
            prefill_len: Some(prefill_len),
            ..llama_opts.clone()
        },
    );
    assert!(r.streaming.is_some());
    assert!(p.streaming.is_some());

    let opts = Options::builder()
        .target(Target::CUDA(PrefetchPolicy::Disabled))
        .build();
    let tokenizer = Tokenizer::from_file(dir.join("tokenizer.json")).unwrap();
    let mut llm = LlmSession::for_llama_streaming(
        r.graph,
        Some((p.graph, prefill_len)),
        r.kv_cache_names,
        tokenizer,
        &opts,
        max_seq_len,
        config.eos_token_id,
        sink,
        window,
    )
    .unwrap();

    let want = max_active + 10;
    let new_ids = llm.generate_ids(PROMPT, want).unwrap();
    assert_eq!(new_ids.len(), want);
    assert!(
        max_active < llm.past_len(),
        "past_len {} must exceed sink+window {} to exercise the ring",
        llm.past_len(),
        max_active,
    );
}

#[cfg(feature = "cuda")]
#[test]
fn cuda_streaming_prefill_runs_past_window() {
    run_streaming_prefill_smoke(false);
}

#[cfg(feature = "cuda")]
#[test]
fn cuda_streaming_quant_prefill_runs_past_window() {
    run_streaming_prefill_smoke(true);
}

#[cfg(feature = "cuda")]
#[test]
fn cuda_bf16() {
    run_bf16(Target::CUDA(PrefetchPolicy::Disabled));
}
