use std::path::Path;
use std::path::PathBuf;

use my_nn_engine::options::Options;
use my_nn_engine::options::Target;
use my_nn_engine_llm::build_llama;
use my_nn_engine_llm::quantize::cast_safetensors_bf16_dir;
use my_nn_engine_llm::HfConfig;
use my_nn_engine_llm::HfWeights;
use my_nn_engine_llm::LlamaWeights;
use my_nn_engine_llm::LlmSession;
use tokenizers::Tokenizer;

fn model_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../models/hf/tiny-llama-random")
}

// Reference generated by `scripts/gen_llm_reference.py models/hf/tiny-llama-random "Hello" 8`.
// The same IDs are produced under bf16 for this small model (verified with
// transformers torch_dtype=bfloat16).
const PROMPT: &str = "Hello";
const EXPECTED_NEW_IDS: &[u32] = &[3038, 25190, 6074, 6566, 21376, 8002, 12090, 28535];

fn run_with_dir(dir: &Path, target: Target) {
    let config = HfConfig::from_path(dir.join("config.json")).unwrap();
    let hf = HfWeights::from_dir(dir).unwrap();
    let weights = LlamaWeights::from_hf(&hf, config.num_hidden_layers).unwrap();

    let max_seq_len = 32;
    let r = build_llama(&config, &weights, max_seq_len);
    let opts = Options::builder().target(target).build();
    let tokenizer = Tokenizer::from_file(dir.join("tokenizer.json")).unwrap();
    let mut llm = LlmSession::for_llama(
        r.graph,
        r.kv_cache_names,
        tokenizer,
        &opts,
        max_seq_len,
        config.eos_token_id,
    )
    .unwrap();

    let new_ids = llm.generate_ids(PROMPT, EXPECTED_NEW_IDS.len()).unwrap();
    assert_eq!(new_ids, EXPECTED_NEW_IDS);
}

fn run(target: Target) {
    run_with_dir(&model_dir(), target);
}

fn run_bf16(target: Target) {
    let src = model_dir();
    let tmp = tempfile::TempDir::new().unwrap();
    cast_safetensors_bf16_dir(&src, tmp.path().join("model.safetensors")).unwrap();
    for name in [
        "config.json",
        "tokenizer.json",
        "generation_config.json",
        "special_tokens_map.json",
        "tokenizer_config.json",
        "chat_template.jinja",
    ] {
        let from = src.join(name);
        if from.exists() {
            std::fs::copy(&from, tmp.path().join(name)).unwrap();
        }
    }
    run_with_dir(tmp.path(), target);
}

#[test]
fn cpu() {
    run(Target::CPU);
}

#[test]
fn cpu_bf16() {
    run_bf16(Target::CPU);
}

#[cfg(feature = "cuda")]
#[test]
fn cuda() {
    run(Target::CUDA);
}

#[cfg(feature = "cuda")]
#[test]
fn cuda_bf16() {
    run_bf16(Target::CUDA);
}
