[package]
name = "my-nn-engine-test-tools"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "my-nn-engine-test-tools"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
my-nn-engine = { path = "../.." }
tempfile = { workspace = true }
