[package]
name = "my-nn-engine-llm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[features]
default = ["cuda"]
cuda = ["my-nn-engine/cuda"]
local = ["my-nn-engine/local"]

[dependencies]
my-nn-engine = { path = "../..", default-features = false }
log = { workspace = true }
thiserror = "2"
tokenizers = { version = "0.20", default-features = false, features = ["onig"] }
serde = { workspace = true }
serde_json = "1.0.149"
safetensors = "0.7.0"
memmap2 = { workspace = true }
libloading = { workspace = true }
itertools = { workspace = true }
minijinja = { version = "2.19.0", default-features = false, features = ["builtins", "serde"] }

[dev-dependencies]
tempfile = { workspace = true }
serial_test = "3"
